In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
# Accuracy: 86.00508905852418%
# Recall: 0.0
# Precision: nan
# F1 Score: nan
# Confusion Matrix:
# [[1014    0]
#  [ 165    0]]


# print(f"Accuracy: {accuracy * 100}%")
# print(f"Recall: {recall}")
# print(f"Precision: {precision}")
# print(f"F1 Score: {f1_score}")
# print(f"Confusion Matrix: \n{confusion_matrix}")
# print(f"Classification Report: \n{classification_report}")


# print(f"Accuracy: {accuracy * 100}%")
# print(f"Recall: {recall}")
# print(f"Precision: {precision}")
# print(f"F1 Score: {f1_score}")
# print(f"Confusion Matrix: \n{confusion_matrix}")
# print(f"Classification Report: \n{classification_report}")


# Accuracy: 87.95589482612384%
# Recall: 0.041379310344827586
# Precision: 0.6666666666666666
# F1 Score: 0.07792207792207793
# Confusion Matrix:
# [[1031    3]
#  [ 139    6]]

In [ ]:
# For df 1_10

# RESULTS FOR RANDOM FOREST
# 0.8744795281054824
# [[10011     0]
#  [ 1447    70]]
# RESULTS FOR LOGISTIC REGRESSION
# 0.8703157529493407
# [[10000    11]
#  [ 1484    33]]