In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('C:/Users/Vartika/Documents/GitHub/Delayma-Models/Datasets/df_1_10.csv')
df.head()

MONTH  DAY_OF_MONTH  DAY_OF_WEEK  OP_UNIQUE_CARRIER  DEST  DEP_DELAY  \
0     11             1            5                  3    28          0   
1     11             1            5                  3    20          1   
2     11             1            5                  3    30          0   
3     11             1            5                  4     1          0   
4     11             1            5                  1    28          0   

   CRS_ELAPSED_TIME  DISTANCE  CRS_DEP_M  DEP_TIME_M  ...  Drizzle  Snow  \
0               371      2475        340         333  ...        0     0   
1               181      1069        301         341  ...        0     0   
2               168       944        345         343  ...        0     0   
3               139       760        360         356  ...        0     0   
4               373      2475        360         359  ...        0     0   

   Wintry Mix  Freezing Rain  MONTH_sin  MONTH_cos  DAY_OF_MONTH_sin  \
0           0              0       -0.5   0.866025          0.201299   
1           0              0       -0.5   0.866025          0.201299   
2           0              0       -0.5   0.866025          0.201299   
3           0              0       -0.5   0.866025          0.201299   
4           0              0       -0.5   0.866025          0.201299   

   DAY_OF_MONTH_cos  DAY_OF_WEEK_sin  DAY_OF_WEEK_cos  
0           0.97953        -0.974928        -0.222521  
1           0.97953        -0.974928        -0.222521  
2           0.97953        -0.974928        -0.222521  
3           0.97953        -0.974928        -0.222521  
4           0.97953        -0.974928        -0.222521  

[5 rows x 36 columns]

In [4]:
# draw heatmap between rain drizzle windy mix and delay
# print correlation matrix
corr = df.corr()
corr


MONTH  DAY_OF_MONTH  DAY_OF_WEEK  OP_UNIQUE_CARRIER  \
MONTH              1.000000     -0.017878     0.029797           0.012424   
DAY_OF_MONTH      -0.017878      1.000000    -0.030224           0.010621   
DAY_OF_WEEK        0.029797     -0.030224     1.000000          -0.000299   
OP_UNIQUE_CARRIER  0.012424      0.010621    -0.000299           1.000000   
DEST              -0.008480     -0.005655    -0.002954          -0.016241   
DEP_DELAY          0.080222     -0.028849     0.015557           0.005474   
CRS_ELAPSED_TIME  -0.011192     -0.010029    -0.008534          -0.084666   
DISTANCE           0.004030     -0.016425    -0.006865          -0.072437   
CRS_DEP_M         -0.004434      0.006790     0.001589           0.020919   
DEP_TIME_M        -0.003564      0.006396     0.004835           0.020405   
CRS_ARR_M         -0.022690      0.013533    -0.005619           0.079333   
Temperature        0.142239     -0.132947     0.009275           0.025342   
Dew Point          0.038173     -0.053812    -0.124569           0.007633   
Humidity           0.014503      0.091405    -0.005944          -0.005887   
Wind               0.010360     -0.221359     0.059497           0.002419   
Wind Speed        -0.035536     -0.083394     0.105962           0.001122   
Wind Gust         -0.051781     -0.086125     0.138714           0.004813   
Pressure          -0.092224      0.011101     0.100276          -0.005320   
sch_dep           -0.009916     -0.001402     0.017623           0.090873   
sch_arr           -0.010239      0.008226     0.009464          -0.024220   
TAXI_OUT           0.037541     -0.007007     0.023768           0.023544   
Cloudy            -0.044892      0.086347     0.078834           0.003784   
Windy             -0.081836     -0.056957     0.115090           0.005369   
Fair              -0.020190     -0.024479     0.014499          -0.007055   
Rain               0.102041     -0.037719    -0.102647           0.006003   
Fog                0.023723     -0.024298     0.020529          -0.002331   
Drizzle           -0.069956     -0.047178    -0.028211           0.009212   
Snow               0.005929     -0.028427    -0.040431          -0.002947   
Wintry Mix         0.043981     -0.052332    -0.028445           0.005110   
Freezing Rain      0.013047     -0.018133     0.007990           0.005875   
MONTH_sin         -0.829255      0.040579    -0.029827          -0.015813   
MONTH_cos          0.561205      0.028108     0.009143          -0.001189   
DAY_OF_MONTH_sin   0.002537     -0.794707     0.011230          -0.010795   
DAY_OF_MONTH_cos  -0.039182      0.088601     0.032245           0.016681   
DAY_OF_WEEK_sin    0.001955      0.006597    -0.725401           0.004478   
DAY_OF_WEEK_cos    0.085532     -0.014011     0.344507           0.002056   

                       DEST  DEP_DELAY  CRS_ELAPSED_TIME  DISTANCE  CRS_DEP_M  \
MONTH             -0.008480   0.080222         -0.011192  0.004030  -0.004434   
DAY_OF_MONTH      -0.005655  -0.028849         -0.010029 -0.016425   0.006790   
DAY_OF_WEEK       -0.002954   0.015557         -0.008534 -0.006865   0.001589   
OP_UNIQUE_CARRIER -0.016241   0.005474         -0.084666 -0.072437   0.020919   
DEST               1.000000  -0.013839          0.683655  0.719088  -0.019605   
DEP_DELAY         -0.013839   1.000000         -0.057109 -0.055931   0.149509   
CRS_ELAPSED_TIME   0.683655  -0.057109          1.000000  0.994927   0.009315   
DISTANCE           0.719088  -0.055931          0.994927  1.000000  -0.002331   
CRS_DEP_M         -0.019605   0.149509          0.009315 -0.002331   1.000000   
DEP_TIME_M        -0.022967   0.156148          0.015236  0.001423   0.949706   
CRS_ARR_M         -0.017344   0.043644          0.035903  0.012812   0.341181   
Temperature        0.001690  -0.023119          0.004320  0.009964   0.089350   
Dew Point          0.000980  -0.008970          0.001128  0.003192  -0.038792   
Humidity           0.007027  -0.032763

In [5]:
# train this model on 80% of the data and test on 20%
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(df, df['DEP_DELAY'], test_size=0.4, random_state=0)

In [6]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

# train the model
random_forest = RandomForestClassifier(n_estimators=6, max_depth=5, random_state=1)
random_forest.fit(xtrain, ytrain)
y_pred = random_forest.predict(xtest)
print(accuracy_score(ytest, y_pred))
# print confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest, y_pred)
print(confusion_matrix(ytest, y_pred))

0.9904046725073008
[[4170    0]
 [  46  578]]


In [7]:
df_2 = pd.read_csv('C:/Users/Vartika/Documents/GitHub/Delayma-Models/Datasets/df_1_25.csv')
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(df_2, df_2['DEP_DELAY'], test_size=0.4, random_state=0)
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

# train the model
random_forest = RandomForestClassifier(n_estimators=6, max_depth=5, random_state=1)
random_forest.fit(xtrain, ytrain)
y_pred = random_forest.predict(xtest)
print(accuracy_score(ytest, y_pred))
# print confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(ytest, y_pred)
print(confusion_matrix(ytest, y_pred))

0.9794053131854741
[[7123    0]
 [ 169  914]]


In [8]:
df_3 = pd.read_csv('C:/Users/Vartika/Documents/GitHub/Delayma-Models/Datasets/df_1_3.csv')
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(df_2, df_2['DEP_DELAY'], test_size=0.4, random_state=0)
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

# train the model
random_forest = RandomForestClassifier(n_estimators=6, max_depth=5, random_state=1)
random_forest.fit(xtrain, ytrain)
y_pred = random_forest.predict(xtest)
print(accuracy_score(ytest, y_pred))
# print confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(ytest, y_pred)
print(confusion_matrix(ytest, y_pred))

0.9794053131854741
[[7123    0]
 [ 169  914]]


In [9]:
df_4 = pd.read_csv('C:/Users/Vartika/Documents/GitHub/Delayma-Models/Datasets/df_preprocessed.csv')
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(df_4, df_4['DEP_DELAY'], test_size=0.4, random_state=0)
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

# train the model
random_forest = RandomForestClassifier(n_estimators=6, max_depth=3, random_state=1)
random_forest.fit(xtrain, ytrain)
y_pred = random_forest.predict(xtest)
print(accuracy_score(ytest, y_pred))
# print confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(ytest, y_pred)
print(confusion_matrix(ytest, y_pred))

0.8893129770992366
[[10011     0]
 [ 1276   241]]


## TRYING REGRESSION

In [10]:
df_regression = pd.read_csv('C:/Users/Vartika/Documents/GitHub/Delayma-Models/Datasets/m1_final_regression_dataset.csv')

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

xtrain, xtest, ytrain, ytest = train_test_split(df_regression, df_regression['DEP_DELAY'], test_size=0.4, random_state=0)
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestRegressor

# train the model
random_forest = RandomForestRegressor(n_estimators=10, max_depth=5, random_state=1)
random_forest.fit(xtrain, ytrain)
y_pred = random_forest.predict(xtest)
ytest = ytest.to_numpy()
# for i in range(len(y_pred)):
    # print(y_pred[i],ytest[i])
# find mean squared error
mean_squared_error = mean_squared_error(y_pred,ytest)
print(mean_squared_error)

11.521809734288023
